name: 'Build and Release Pipelines $(Date:yyyy-MM-dd)_v$(Rev:rr)'

pr: none
trigger: none
  # branches:
  #   include:
  #   - dev
  #   - main
  # paths:
  #   include:
  #   - 'service_principal-managed_identity'

    
variables: 
- group: 'service-connection'
- group: 'my_publicIP'
- name: system.debug
  value: 'true'
- name: RGName
  value: "rg-ADO-2"            
- name: StorageAccName
  value: "mystorageacct16425"  
- name: ContainerName
  value: "storage-container"         
- name: ADO_Environment
  value: "Staging"
- name: Pipeline_Agent
  value: 'My Agents'
- name: SKIPPED_CHECKS
  value: 'CKV_TF_1,CKV_AZURE_249'

  # Using build_template or ci_template pipeline based on branch condition
stages: 
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:  
  - template: pipeline_templates/release_template.yml
    parameters:  
      TerraformDirectory: 'service_principal-managed_identity'
      infrastructure: 'spn_identity'
      tfplan: 'spn.tfplan'
      BlobName: 'spn.tfstate'
- ${{ else }}:
  - template: pipeline_templates/build_template.yml
    parameters: 
      TerraformDirectory: 'service_principal-managed_identity'
      infrastructure: 'spn_identity'
      tfplan: 'spn.tfplan'
      BlobName: 'spn.tfstate'